/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.rjgodoy.plan111mil.torneo.ui;

import ar.com.rjgodoy.plan111mil.torneo.Aplicacion;

/**
 *
 * @author Javier
 */
public class FramePrincipal extends javax.swing.JFrame {

	private final Aplicacion aplicacion;

    /**
     * Creates new form FramePrincipal
     */
	public FramePrincipal(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministradorTorneo = new javax.swing.JButton();
        btnResponsableSecretariaDeportes = new javax.swing.JButton();
        btnResponsableInscripciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Torneos");

        btnAdministradorTorneo.setText("Administrador Torneo");
        btnAdministradorTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorTorneoActionPerformed(evt);
            }
        });

        btnResponsableSecretariaDeportes.setText("Responsable Secretaría de Deportes");
        btnResponsableSecretariaDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsableSecretariaDeportesActionPerformed(evt);
            }
        });

        btnResponsableInscripciones.setText("Responsable de Inscripciones");
        btnResponsableInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsableInscripcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdministradorTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResponsableSecretariaDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(btnResponsableInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAdministradorTorneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResponsableSecretariaDeportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResponsableInscripciones)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorTorneoActionPerformed
		new FrameAdministradorTorneo(aplicacion).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_btnAdministradorTorneoActionPerformed

    private void btnResponsableSecretariaDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsableSecretariaDeportesActionPerformed
		new FrameResponsableSecretaria(aplicacion).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_btnResponsableSecretariaDeportesActionPerformed

    private void btnResponsableInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsableInscripcionesActionPerformed
		new FrameResponsableInscripciones(aplicacion).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_btnResponsableInscripcionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministradorTorneo;
    private javax.swing.JButton btnResponsableInscripciones;
    private javax.swing.JButton btnResponsableSecretariaDeportes;
    // End of variables declaration//GEN-END:variables
}
