/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.rjgodoy.plan111mil.torneo.ui;

import static ar.com.rjgodoy.plan111mil.torneo.ui.UiUtils.validarRequerido;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;

import javax.swing.DefaultListModel;

import ar.com.rjgodoy.plan111mil.torneo.modelo.Categoria;
import ar.com.rjgodoy.plan111mil.torneo.modelo.Competencia;
import ar.com.rjgodoy.plan111mil.torneo.modelo.Disciplina;
import ar.com.rjgodoy.plan111mil.torneo.modelo.Torneo;
import ar.com.rjgodoy.plan111mil.torneo.servicios.GestorCategoria;
import ar.com.rjgodoy.plan111mil.torneo.servicios.GestorCompetencia;
import ar.com.rjgodoy.plan111mil.torneo.servicios.GestorDisciplina;
import ar.com.rjgodoy.plan111mil.torneo.servicios.GestorTorneo;

/**
 * CU08 Registrar Competencia
 * 
 * @author Javier
 */
public class RegistrarCompetenciaFrame extends javax.swing.JFrame {

	private final GestorTorneo gestorTorneo;
	private final GestorDisciplina gestorDisciplina;
	private final GestorCategoria gestorCategoria;
	private final GestorCompetencia gestorCompetencia;

    /**
	 * Creates new form RegistrarSedeFrame
	 */
	public RegistrarCompetenciaFrame(GestorTorneo gestorTorneo, GestorDisciplina gestorDisciplina,
			GestorCategoria gestorCategoria, GestorCompetencia gestorCompetencia) {
		this.gestorTorneo = gestorTorneo;
		this.gestorDisciplina = gestorDisciplina;
		this.gestorCategoria = gestorCategoria;
		this.gestorCompetencia = gestorCompetencia;
		initComponents();
		initComboTorneo();
		initComboDisciplina();
		initListaCategorias();
		tfFecha.setValue(new Date());
    }


	private void initComboTorneo() {
		for (Torneo torneo : gestorTorneo.listarTorneos()) {
			cbTorneo.addItem(torneo);
		}
	}

	private void initComboDisciplina() {
		for (Disciplina disciplina : gestorDisciplina.listarDisciplinas()) {
			cbDisciplina.addItem(disciplina);
		}
	}

	private void initListaCategorias() {
		DefaultListModel<Categoria> model = new DefaultListModel<Categoria>();
		for (Categoria categoria : gestorCategoria.listarCategorias()) {
			model.addElement(categoria);
		}
		listCategorias.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        cbTorneo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDisciplina = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Competencia");

        jLabel1.setText("Torneo");

        btnCancelar.setText("Cancelar");
        btnCancelar.setName(""); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setName(""); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Disciplina");

        jLabel3.setText("Fecha");

        tfFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        jLabel4.setText("Categorías");

        jScrollPane1.setViewportView(listCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTorneo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
		Competencia competencia = new Competencia();
		competencia.setTorneo((Torneo) cbTorneo.getSelectedItem());
		if (!validarRequerido("Torneo", competencia.getTorneo())) {
			return;
		}

		competencia.setDisciplina((Disciplina) cbDisciplina.getSelectedItem());
		if (!validarRequerido("Disciplina", competencia.getDisciplina())) {
			return;
		}

		competencia.setCategorias(new HashSet<>(listCategorias.getSelectedValuesList()));
		if (competencia.getCategorias().isEmpty()) {
			UiUtils.mostrarErrorValidacion("Debe seleccionar al menos una categoría");
			return;
		}

		String strFechaInicio = tfFecha.getText();
		if (!validarRequerido("Fecha", strFechaInicio)) {
			return;
		}

		try {
			SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
			competencia.setInicio(sdf.parse(strFechaInicio));
		} catch (ParseException e) {
			UiUtils.mostrarErrorValidacion("La Fecha ingresada es incorrecta");
			return;
		}

		gestorCompetencia.registrarCompetencia(competencia);
		dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Disciplina> cbDisciplina;
    private javax.swing.JComboBox<Torneo> cbTorneo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Categoria> listCategorias;
    private javax.swing.JFormattedTextField tfFecha;
    // End of variables declaration//GEN-END:variables
}
